import React from 'react';
import { 
  ArrowRight, 
  Landmark, 
  Gavel, 
  Bot, 
  ShieldCheck, 
  FileText, 
  Share2, 
  Star, 
  LayoutDashboard, 
  Library, 
  Settings, 
  HelpCircle, 
  LogOut, 
  Bell, 
  Search, 
  ChevronDown, 
  ChevronRight,
  Newspaper, 
  ClipboardCheck, 
  BookOpen, 
  FileEdit, 
  Play, 
  Download, 
  AlertCircle, 
  Calendar, 
  Paperclip, 
  Send, 
  User, 
  Building2, 
  ShieldAlert, 
  CheckCircle2, 
  BarChart3,
  FolderOpen,
  CalendarDays,
  Wallet,
  Building,
  BadgeCheck,
  Fingerprint,
  Receipt,
  UserCircle,
  Timer,
  CreditCard,
  Mail,
  Hourglass,
  Copyright,
  PenTool,
  ShieldQuestion,
  Headset,
  Verified,
  Info,
  Archive,
  Filter,
  History,
  Lock,
  Bitcoin,
  Rocket,
  MapPin,
  Map,
  GraduationCap,
  Award,
  ScrollText,
  Shield,
  Users,
  CalendarCheck,
  TrendingUp,
  Clock,
  Video,
  Phone,
  Sparkles,
  FolderSync,
  Plus,
  Scale,
  CheckCheck, 
  AlertTriangle, 
  MessageSquare, 
  MoreVertical,
  ChevronLeft,
  Globe,
  DoorOpen,
  ExternalLink,
  Languages,
  Truck,
  Server,
  XCircle,
  X,
  Activity,
  ChevronsUpDown,
  Check,
  ArrowLeft,
  Lightbulb,
  RefreshCw
} from 'lucide-react';

const iconMap = {
  'sync': RefreshCw,
  'local_shipping': Truck,
  'arrow_forward': ArrowRight,
  'account_balance': Landmark,
  'gavel': Gavel,
  'smart_toy': Bot,
  'verified_user': ShieldCheck,
  'description': FileText,
  'hub': Share2,
  'star': Star,
  'dashboard': LayoutDashboard,
  'library_books': Library,
  'settings': Settings,
  'help': HelpCircle,
  'help_outline': HelpCircle,
  'logout': LogOut,
  'notifications': Bell,
  'search': Search,
  'expand_more': ChevronDown,
  'chevron_right': ChevronRight,
  'article': Newspaper,
  'fact_check': ClipboardCheck,
  'menu_book': BookOpen,
  'contract_edit': FileEdit,
  'play_arrow': Play,
  'download': Download,
  'priority_high': AlertCircle,
  'event': Calendar,
  'event_note': CalendarDays,
  'calendar_today': Calendar,
  'attach_file': Paperclip,
  'send': Send,
  'person': User,
  'corporate_fare': Building2,
  'shield_lock': ShieldAlert,
  'check_circle': CheckCircle2,
  'analytics': BarChart3,
  'folder_open': FolderOpen,
  'account_balance_wallet': Wallet,
  'business': Building,
  'protocol': ShieldCheck,
  'strategy': ShieldCheck,
  'architecture': Building2, // Legacy - avoid using
  'category': LayoutDashboard,
  'support_agent': Headset,
  'copyright': Copyright,
  'draw': PenTool,
  'policy': ShieldQuestion,
  'insights': BarChart3,
  'mail': Mail,
  'hourglass_empty': Hourglass,
  'verified': Verified,
  'badge': BadgeCheck,
  'fingerprint': Fingerprint,
  'receipt_long': Receipt,
  'account_circle': UserCircle,
  'schedule': Timer,
  'payments': CreditCard,
  'info': Info,
  'inventory_2': Archive,
  'filter_list': Filter,
  'history': History,
  'lock': Lock,
  'shield': ShieldCheck,
  'currency_bitcoin': Bitcoin,
  'rocket_launch': Rocket,
  'location_on': MapPin,
  'school': GraduationCap,
  'workspace_premium': Award,
  'history_edu': ScrollText,
  'balance': Scale,
  'security': Shield,
  'group': Users,
  'event_available': CalendarCheck,
  'trending_up': TrendingUp,
  'video_call': Video,
  'call': Phone,
  'auto_awesome': Sparkles,
  'folder_shared': FolderSync,
  'contact_support': HelpCircle,
  'chevron_left': ChevronLeft,
  'language': Globe,
  'videocam': Video,
  'person_outline': User,
  'calendar_month': CalendarDays,
  'meeting_room': DoorOpen,
  'open_in_new': ExternalLink,
  'server': Server,
  'done_all': CheckCheck,
  'more_vert': MoreVertical,
  'warning': AlertTriangle,
  'forum': MessageSquare,
  'add': Plus,
  'update': History,
  'video_library': Video,
  'map': Map,
  'cancel': XCircle,
  'close': X,
  'monitor_heart': Activity,
  'task_alt': CheckCircle2,
  'unfold_more': ChevronsUpDown,
  'check': Check,
  'arrow_back': ArrowLeft,
  'lightbulb': Lightbulb,
  'info_outline': Info
};

const Icon = ({ name, size = 20, className = '', color = 'currentColor', strokeWidth = 2, ...props }) => {
  const LucideIcon = iconMap[name] || HelpCircle;
  
  return (
    <LucideIcon 
      size={size} 
      className={className} 
      color={color} 
      strokeWidth={strokeWidth}
      {...props}
    />
  );
};

export default Icon;
